
version: '3.2'
services:
  maven-web-app:
    image:  dockerjaikay/springapp
    networks:
      - jaikay
    ports:
      - 8888:8080
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=devdb
    - MONGO_DB_PASSWORD=devdb123
  mongo:
    image:  mongo
    networks:
      - jaikay
    volumes:
      - jacks
    environment:
    - MONGO_INITDB_ROOT_USERNAME=devdb
    - MONGO_INITDB_ROOT_PASSWORD=devdb123
networks:
  jaikay:
    external:  true
volumes:
  jacks:
    external:  true
